### ISSUE TITLE
no available machines 뜹니다

### ISSUE THREAD

**Issue by jiyoonbaekbaek** [DatathonInfo/AIDD2021#33]
제출하려고 하는데  no available machines 뜹니다 .. 
![스크린샷 2021-11-19 오후 9 31 42](https://user-images.githubusercontent.com/67775336/142623326-ceabeb57-f927-4b46-9c36-dc49f138624c.png)
!

**Comment by DatathonInfo** [comment]
안녕하세요 참가자님,

현재 다른 팀원분께서 사용 중이신 것 같습니다. 확인 부탁드리겠습니다.

감사합니다.

A.I.D.D. 2021 운영팀 드림.
