### ISSUE TITLE
nia_dm permission denied

### ISSUE THREAD

**Issue by kdha0727** [DatathonInfo/AIDD2021#70]
<img width="728" alt="image" src="https://user-images.githubusercontent.com/61076953/143519151-bd64ba9f-442a-4e1d-9a65-3e062ca05407.png">

## 위와 같은 `Permission Denied` 오류가 지속적으로 발생 중인데 , 확인 부탁드리겠습니다 .

# 감사합니다 .

**Comment by sunnys-lab** [comment]
기 설치된 nsml 때문일지도 모르겠습니다.

일단 nsml 삭제하도록 하겠습니다~

재 발생시 연락주세요~

2021년 11월 26일 (금) 11:51, dhakim ***@***.***>님이 작성:

**Comment by sunnys-lab** [comment]
앗 깃헙 이슈에 등록된 것을 모르고 제가 답변을 드렸네요~ 죄송합니다. 제가 보낸 갑변은 무시하여주세요~

2021년 11월 26일 (금) 11:51, dhakim ***@***.***>님이 작성:

**Comment by orangeishur** [comment]
권한 부여 다시 해드렸습니다.
재 로그인 후 확인 부탁 드립니다.

**Comment by orangeishur** [comment]
다른 팀원 분들도 동일한 증상인지 확인 부탁 드립니다.

**Comment by orangeishur** [comment]
A.I.D.D. 2021 - NSML 담당자 입니다. 
대회 시작 시간(14:00)에 맞춰 권한을 드린거라 대회 전에는 접근이 불가한게 맞습니다.
현재는 정상 접근 확인하였습니다. 그럼 좋은 결과 있기를 바랍니다. 감사합니다.
