### ISSUE TITLE
순위 볼수 있는 페이지 문의

### ISSUE THREAD

**Issue by young31** [DatathonInfo/AIDD2021#8]
예전에 비슷한 대회 참여할 때 
제출시 session 정보와 리더보드 보는 부분이 있었던 것 같은데
혹시 안내해주실 수 있나요?

**Comment by DatathonInfo** [comment]
안녕하세요, 참가자님.

대회 리더보드는 https://ai.nsml.navercorp.com/rankings/3 에서 확인 가능합니다.

아울러 세션 정보는 nsml 웹 ai.nsml.navercorp.com 에 로그인하신 후 확인하시면 됩니다.

감사합니다.
A.I.D.D 2021 운영팀
